Update README.md
kalviumcommunity/brickel pull request #1
Opened 2023-02-23 06:19 UTC by popeinabar

2023-02-23 06:38 UTC, PatelNeelMahesh approved these changes
Keep updating the readme file as you add more features,
Give description for PR.
Give meaningful commit message.

You can merge pull request.

2023-03-13 12:34 UTC, aditya-190 requested changes
We applaud Ayush for your impressive start!. To ensure that the project continues to meet high standards, a few changes are necessary before merging. Please implement these changes and submit updated PR. We appreciate your hard work and look forward to your continued contributions to the project.

2023-03-13 12:34 UTC, aditya-190 commented on package.json
> +  "name": "react-apps",
Pls replace `name` with your `project-name` i.e. - `brickel`

2023-03-13 12:34 UTC, aditya-190 commented on package.json
> +    "@testing-library/jest-dom": "^5.16.5",
testing libraries can be added in `devDependencies` or you can even remove them as you will be not using them for now.

2023-03-13 12:34 UTC, aditya-190 commented on public/index.html
> +    <title>React App</title>
Update title to be your `project-name`

2023-03-13 12:34 UTC, aditya-190 commented on public/manifest.json
> +  "icons": [
Icons can be removed as they are redundant.

2023-03-13 12:34 UTC, aditya-190 commented on public/manifest.json
> +  "name": "Create React App Sample",
Add your `project-name` here

2023-03-13 12:34 UTC, aditya-190 commented on src/About.js
> +      <NavBar></NavBar>
Replace it with <NavBar />

2023-03-13 12:34 UTC, aditya-190 commented on src/App.js
> +    <NavBar></NavBar>
Replace it with <NavBar />

2023-03-13 12:34 UTC, aditya-190 commented on src/App.test.js
> +import App from './App';
This file can be removed.

2023-03-13 12:34 UTC, aditya-190 commented on src/Home.js
> +        <NavBar></NavBar>
Why `NavBar` is used inside `Home.js` when you have already defined it before Routes in `App.js` ?

2023-03-13 12:34 UTC, aditya-190 commented on src/Learn.js
> +          <Serch/>
Please fix the misspelled word - `Search`

2023-03-13 12:34 UTC, aditya-190 commented on src/component/HeroSec2.js
> +    <Link to={'./learn'}>
Please change i to be `/learn`

2023-03-13 12:34 UTC, aditya-190 commented on src/data.js
> +
You can delete this file if you are not using this component.

2023-03-13 12:34 UTC, aditya-190 commented on src/index.js
> +reportWebVitals();
This can be removed as you will not be using this in your project for now.

2023-03-22 10:38 UTC, merged